/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nilai;

/**
 *
 * @author LENOVO
 */
public class Form_Nilai extends javax.swing.JFrame {

    /**
     * Creates new form Form_Nilai
     */
    public Form_Nilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tugas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        hasil_tugas = new javax.swing.JTextField();
        uts = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hasil_uts = new javax.swing.JTextField();
        uas = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        hasil_uas = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        nilai_akhir = new javax.swing.JTextField();
        nilai_huruf = new javax.swing.JTextField();
        predikat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_nilai = new javax.swing.JTable();
        save = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.green);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Program Nilai Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("NIM");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("Nilai Tugas");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.red);
        jLabel5.setText("Nilai UTS");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.red);
        jLabel6.setText("Nilai UAS");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setForeground(java.awt.Color.red);
        jLabel7.setText("Nilai Akhir");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setForeground(java.awt.Color.red);
        jLabel8.setText("Nilai Huruf");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setForeground(java.awt.Color.red);
        jLabel9.setText("Predikat");

        tugas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tugas.setForeground(java.awt.Color.red);
        tugas.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 3, true));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel10.setForeground(java.awt.Color.red);
        jLabel10.setText("20%");

        hasil_tugas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        hasil_tugas.setForeground(java.awt.Color.red);
        hasil_tugas.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 3, true));

        uts.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        uts.setForeground(java.awt.Color.red);
        uts.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 3, true));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel11.setForeground(java.awt.Color.red);
        jLabel11.setText("35%");

        hasil_uts.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        hasil_uts.setForeground(java.awt.Color.red);
        hasil_uts.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 3, true));

        uas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        uas.setForeground(java.awt.Color.red);
        uas.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 3, true));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setForeground(java.awt.Color.red);
        jLabel12.setText("45%");

        hasil_uas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        hasil_uas.setForeground(java.awt.Color.red);
        hasil_uas.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 3, true));

        nim.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nim.setForeground(java.awt.Color.red);
        nim.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 3, true));

        nama.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nama.setForeground(java.awt.Color.red);
        nama.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 3, true));

        nilai_akhir.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nilai_akhir.setForeground(java.awt.Color.red);
        nilai_akhir.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 3, true));
        nilai_akhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilai_akhirActionPerformed(evt);
            }
        });

        nilai_huruf.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nilai_huruf.setForeground(java.awt.Color.red);
        nilai_huruf.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 3, true));

        predikat.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        predikat.setForeground(java.awt.Color.red);
        predikat.setBorder(new javax.swing.border.LineBorder(java.awt.Color.red, 3, true));

        tabel_nilai.setForeground(java.awt.Color.magenta);
        tabel_nilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Nilai Tugas", "Nilai UTS", "Nilai UAS", "Nilai Akhir", "Nilai Huruf", "Predikat"
            }
        ));
        jScrollPane1.setViewportView(tabel_nilai);

        save.setBackground(java.awt.Color.cyan);
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/save.png"))); // NOI18N
        save.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel13.setForeground(java.awt.Color.green);
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tabel Nilai Mahasiswa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(save))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(predikat)
                                .addComponent(nilai_huruf)
                                .addComponent(nilai_akhir)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nim, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(uas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel12)
                                            .addGap(18, 18, 18)
                                            .addComponent(hasil_uas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(uts, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(hasil_uts, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(tugas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel10)
                                            .addGap(18, 18, 18)
                                            .addComponent(hasil_tugas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(hasil_tugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(uts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(hasil_uts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(uas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(hasil_uas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(save)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nilai_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nilai_huruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addComponent(predikat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel9))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel13)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String textnim = nim.getText();
        String textnama = nama.getText();
        
        String texttugas = tugas.getText();
        String textuts = uts.getText();
        String textuas = uas.getText();
        
        float tugas = Integer.parseInt(texttugas);
        float uts = Integer.parseInt(textuts);
        float uas = Integer.parseInt(textuas);
        
        float ntugas, nuts, nuas, nakhir;
        ntugas = tugas * 20 / 100;
        nuts = uts * 35 / 100; 
        nuas = uas * 45 / 100;
        nakhir = ntugas + nuts + nuas;
        
        hasil_tugas.setText("" + ntugas);
        hasil_uts.setText("" + nuts);
        hasil_uas.setText("" + nuas);
        nilai_akhir.setText("" + nakhir);
        
//        nilai_huruf
        if(nakhir>=85){
            nilai_huruf.setText("A");
            predikat.setText("Sangat Baik");
        }else if(nakhir<85 && nakhir>=75){
            nilai_huruf.setText("B");
            predikat.setText("Cukup Baik");
        }else if(nakhir<75 && nakhir>=65){
            nilai_huruf.setText("C");
            predikat.setText("Cukup");
        }else if(nakhir<65 && nakhir>=50){
            nilai_huruf.setText("D");
            predikat.setText("Cukup Jelek");
        }else{
            nilai_huruf.setText("E");
            predikat.setText("Sangat Jelek");
        }
        
//        table
         tabel_nilai.setValueAt(textnim, 0, 0);
         tabel_nilai.setValueAt(textnama, 0, 1);
         tabel_nilai.setValueAt(hasil_tugas.getText(), 0, 2);
         tabel_nilai.setValueAt(hasil_uts.getText(), 0, 3);
         tabel_nilai.setValueAt(hasil_uas.getText(), 0, 4);
         tabel_nilai.setValueAt(nilai_akhir.getText(), 0, 5);
         tabel_nilai.setValueAt(nilai_huruf.getText(), 0, 6);
         tabel_nilai.setValueAt(predikat.getText(), 0, 7);
    }//GEN-LAST:event_saveActionPerformed

    private void nilai_akhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilai_akhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilai_akhirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hasil_tugas;
    private javax.swing.JTextField hasil_uas;
    private javax.swing.JTextField hasil_uts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nilai_akhir;
    private javax.swing.JTextField nilai_huruf;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField predikat;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel_nilai;
    private javax.swing.JTextField tugas;
    private javax.swing.JTextField uas;
    private javax.swing.JTextField uts;
    // End of variables declaration//GEN-END:variables
}
